export const ALL_HOMES_REQUEST  = 'ALL_HOMES_REQUEST'
export const ALL_HOMES_SUCCESS  = 'ALL_HOMES_SUCCESS'
export const ALL_HOMES_FAIL     = 'ALL_HOMES_FAIL'

export const HOME_DETAILS_SUCCESS = 'HOME_DETAILS_SUCCESS'
export const HOME_DETAILS_FAIL = 'HOME_DETAILS_FAIL'

export const HOME_LIST_REQUEST = 'HOME_LIST_REQUEST';
export const HOME_LIST_SUCCESS = 'HOME_LIST_SUCCESS';
export const HOME_LIST_FAIL = 'HOME_LIST_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
