# Generated by Django 4.0.3 on 2022-06-19 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('dis_id', models.AutoField(primary_key=True, serialize=False)),
                ('dis_name', models.CharField(blank=True, max_length=255, null=True)),
                ('city_id', models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cities')),
            ],
            options={
                'db_table': 'districts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('prov_id', models.AutoField(primary_key=True, serialize=False)),
                ('prov_name', models.CharField(blank=True, max_length=255, null=True)),
                ('locationid', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'provinces',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subdistricts',
            fields=[
                ('subdis_id', models.AutoField(primary_key=True, serialize=False)),
                ('subdis_name', models.CharField(blank=True, max_length=255, null=True)),
                ('dis_id', models.ForeignKey(blank=True, db_column='dis_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.districts')),
            ],
            options={
                'db_table': 'subdistricts',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cities',
            name='prov_id',
            field=models.ForeignKey(blank=True, db_column='prov_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.provinces'),
        ),
    ]
